# Generated by Django 2.1.3 on 2018-12-03 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0002_auto_20181201_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('agenda_fecha', models.DateField()),
                ('agenda_creacion', models.DateField(auto_now=True)),
                ('agenda_comentario', models.CharField(max_length=200)),
                ('agenda_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='hora_agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Hora'),
        ),
    ]
