# Generated by Django 2.1.3 on 2018-12-08 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('agenda_fecha', models.DateField()),
                ('agenda_creacion', models.DateField(auto_now=True)),
                ('agenda_comentario', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AgendaTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda_tipo', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoAgenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_agenda', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='agenda_hora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Hora'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='agenda_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.Paciente'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='agenda_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.AgendaTipo'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='estado_agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.EstadoAgenda'),
        ),
    ]
