# Generated by Django 2.1.3 on 2018-12-04 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_estadoagenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='estado_agenda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agenda.EstadoAgenda'),
            preserve_default=False,
        ),
    ]
